mutation DeleteRecipe($id: RecipeId!) {
  deleteRecipe(id: $id)
}

mutation DeleteVersion($recipeId: RecipeId!, $number: VersionNumber!) {
  deleteVersion(recipeId: $recipeId, number: $number)
}

mutation CopyVersion($recipeId: RecipeId!, $number: VersionNumber!, $title: RecipeTitle!) {
  copyVersion(recipeId: $recipeId, number: $number, title: $title) {
    id
  }
}

mutation UpdateRecipe($id: RecipeId!, $input: UpdateRecipeInput!) {
  updateRecipe(id: $id, input: $input) {
    id
    title
    category
  }
}

mutation UpdateFavorite($recipeId: RecipeId!, $versionNumber: VersionNumber!, $favorite: Boolean!) {
  updateFavorite(recipeId: $recipeId, versionNumber: $versionNumber, favorite: $favorite) {
    ...VersionFields
  }
}

mutation UpdateWarnings(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $warnings: [Warning!]!
) {
  updateWarnings(recipeId: $recipeId, versionNumber: $versionNumber, warnings: $warnings) {
    ...VersionFields
  }
}

mutation UpdateRating($recipeId: RecipeId!, $versionNumber: VersionNumber!, $rating: Rating!) {
  updateRating(recipeId: $recipeId, versionNumber: $versionNumber, rating: $rating) {
    ...VersionFields
  }
}

mutation UpdateCoffeeParameters(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $parameters: CoffeeParametersInput!
) {
  updateCoffeeParameters(
    recipeId: $recipeId
    versionNumber: $versionNumber
    parameters: $parameters
  ) {
    ...VersionFields
  }
}

mutation UpdateOvenProfile(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $oven: OvenProfileInput
) {
  updateOvenProfile(recipeId: $recipeId, versionNumber: $versionNumber, oven: $oven) {
    number
  }
}

mutation LinkComponent($recipeId: RecipeId!, $component: RecipeId!, $scale: ComponentScale!) {
  linkComponent(recipeId: $recipeId, component: $component, scale: $scale) {
    id
  }
}

mutation UnlinkComponent($recipeId: RecipeId!, $component: RecipeId!) {
  unlinkComponent(recipeId: $recipeId, component: $component) {
    id
  }
}

mutation UpdateIngredients(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $ingredients: [IngredientInput!]!
) {
  updateIngredients(recipeId: $recipeId, versionNumber: $versionNumber, ingredients: $ingredients) {
    number
  }
}

mutation UpdateMiseEnPlace(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $miseEnPlace: [StepText!]!
) {
  updateMiseEnPlace(recipeId: $recipeId, versionNumber: $versionNumber, miseEnPlace: $miseEnPlace) {
    number
  }
}

mutation UpdateSteps(
  $recipeId: RecipeId!
  $versionNumber: VersionNumber!
  $steps: [VersionStepInput!]!
) {
  updateSteps(recipeId: $recipeId, versionNumber: $versionNumber, steps: $steps) {
    number
  }
}
